### ISSUE TITLE
CN realms

### ISSUE THREAD

**Issue by Darthpred** [phanx-wow/LibRealmInfo#14]
Hi. This time it seems like I have more people from China using my stuff than everyone else :D 

So I got complains about error in the lib today
`LibRealmInfo\LibRealmInfo-12.lua:28: bad argument #1 to '(for generator)' (table expected, got nil)`

the table in question is realm.connections which is basically non-existent for CN.

Was not able to get any useful info (e.g. resulting ID for connected realms) from people complaining so I had to work with what I had. I made a work around for it by adding a check in shallowCopy function. Now it looks like:
```
local function shallowCopy(t)
	local n = {}
	if t then
		for k, v in next, t do
			n[k] = v
		end
	end
	return n
end
```

So when the arg passed is nil (e.g. China) the function will just return empty table instead and not try to dig through nil

I got the list of connected realms on wowpedia though, not much help but still https://wow.gamepedia.com/Connected_Realms#China_region

**Comment by Phanx** [comment]
Given how few realms are listed on Wowpedia vs. how many Chinese realms there actually are, I'm going to go out on a limb and guess that that data is incomplete at best, and not of much use.

As a partial workaround for this particular problem, I can auto-fill the data for the player's current realm and any connected realms by querying `GetAutoCompleteRealms()`. Would that be helpful for your addon?

**Comment by Darthpred** [comment]
In my case it doesn't really matter. My addon does specific stuff only for US/EU region. So I don't need the complete data for asian realms all together. So what I made for myself works just fine.

I just posted a ticket to let you know of a possibility this can happen in some cases.

**Comment by Phanx** [comment]
Fixed, and added the partial workaround since it may be helpful for someone.
