### ISSUE TITLE
GetRealmInfo(name[, region]) error

### ISSUE THREAD

**Issue by GreyFoxGer** [phanx-wow/LibRealmInfo#18]
Im trying to load an party1 stuff, but have this error on player login (reload UI fixes it)

here is my code

`local _, name, _, _, locale, _, region, _, _, _, _ = LibRealmInfo:GetRealmInfoByUnit('party1')
	if region == "EU" then
		if locale == "ptBR" then
my stuff
        end
end` any help please? :)

**Comment by Phanx** [comment]
WoW doesn't know about anyone's GUID on a fresh login until the PLAYER_LOGIN event fires. If your code depends on GUIDs or anything derived from them, you need to wait until PLAYER_LOGIN fires to run it.
